//Try… Catch—finally is used to handle exceptions in the JavaScript
try{
        // Code
    }
    catch(exp){
    // Code to throw an exception.
}
finally{
    // Code runs either it finishes successfully or after catch
}
